### ISSUE TITLE
Python linting & formatting

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/build-tools#50]
flake8 and https://github.com/google/yapf

**Comment by jml** [comment]
This came up again today in weaveworks/service-conf#537

**Comment by jml** [comment]
Just experimented with yapf for grafanalib. It doesn't work well with Python 3 –
 https://github.com/google/yapf/issues/342

We mostly don't care about Python 3, so we should probably go ahead. I'd like to have some input on [how we configure it](https://github.com/google/yapf#knobs).
